sudo: false
language: cpp
matrix:
  - VERSION:
    - 1.2.0
    - 1.3.0
    - 1.4.0   
script:
  - PROJECT_NAME="esp-alt-sdk"
  - VENDOR_SDK_VERSION=$VERSION
  - PLATFORM="windows"
  - ARCH="x86_64"
  - FILENAME="${PROJECT_NAME}-${VERSION}-${PLATFORM}-${ARCH}.tar.gz"  
  - make VENDOR_SDK_VERSION=$VERSION