sudo: false
language: cpp
os:
  - linux
  - osx
env:
  matrix:
    - VERSION:
      - 1.2.0
      - 1.3.0
      - 1.4.0
     exclude:
    - os: osx
      env: PLATFORM="mac"
    - os: linux
      env: PLATFORM="mac"
script:
  - PROJECT_NAME="esp-alt-sdk"
  - VENDOR_SDK_VERSION=$VERSION  
  - ARCH="x86_64"
  - FILENAME="${PROJECT_NAME}-${VERSION}-${PLATFORM}-${ARCH}.tar.gz"  
  - make VENDOR_SDK_VERSION=$VERSION