sd
language: cpp
os:
  - linux
  - osx
env:
  matrix:
    - VERSION=1.2.0
    language: cpp
    - VERSION=1.3.0
    language: cpp
    - VERSION=1.4.0    
    language: cpp
cache:
  directories:
  - src/
script:
  - PLATFORM=$TRAVIS_OS_NAME
  - PROJECT_NAME="esp-alt-sdk"
  - VENDOR_SDK_VERSION=$VERSION  
  - FILENAME="${PROJECT_NAME}-${VERSION}-${PLATFORM}-${ARCH}.tar.gz"  
  - make clean
  - make VENDOR_SDK_VERSION=$VERSION