language: cpp
os:
  - linux
  - osx
env:
  matrix:
    - VERSION=1.2.0
    - VERSION=1.3.0
    - VERSION=1.4.0
cache:
  directories:
  - src/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
      - texinfo
      - unrar
      - unzip      
      - libtool
      - gcc
      - gperf
      - flex
      - bison
      - texinfo
      - gawk
      - python
      - python-serial
      - sed
      - git
      - gcc-multilib
      - g++-multilib
      - mono-complete
      - bsdtar
# install:
#   - cd env/; make

script:
  - cd $TRAVIS_BUILD_DIR
  - automake --version
  - autoconf --version
  - g++ --version
  - gcc --version
  - PLATFORM=$TRAVIS_OS_NAME
  - PROJECT_NAME="esp-alt-sdk"
  - VENDOR_SDK_VERSION=$VERSION  
  - FILENAME="${PROJECT_NAME}-${VERSION}-${PLATFORM}-${ARCH}.tar.gz"    
  - echo $PWD
  - make clean
  - make VENDOR_SDK_VERSION=$VERSION PREBUILT_TOOLCHAIN=y