os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf false
environment:
  matrix:
    - build_platform: "x86"
      build_compiler: "mingw"
      build_bindings: 1
      VERSION: 1.2.0
    - build_platform: "x86"
      build_compiler: "mingw"
      build_bindings: 1
      VERSION: 1.3.0
    - build_platform: "x86"
      build_compiler: "mingw"
      build_bindings: 1
      VERSION: 1.4.0

    - build_platform: "x64"
      build_compiler: "mingw"
      build_bindings: 1
      VERSION: 1.2.0
    - build_platform: "x64"
      build_compiler: "mingw"
      build_bindings: 1
      VERSION: 1.3.0
    - build_platform: "x64"
      build_compiler: "mingw"
      build_bindings: 1
      VERSION: 1.4.0
cache:
  - src  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
install:
  - echo %VERSION%
  - dir C:\MinGW\msys\1.0\bin\
  # - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c 'ls -la /'
  - C:\MinGW\bin\mingw-get install mingw32-base mingw32-mgwport mingw32-pdcurses mingw32-make mingw-developer-toolkit mingw32-gdb gcc gcc-c++ libz bzip2
  - C:\MinGW\bin\mingw-get install msys-patch msys-zip
  - C:\MinGW\bin\mingw-get remove autoconf
  - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c 'cd /c/projects/%APPVEYOR_PROJECT_NAME%/env; make'

build_script:
  # - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c "PATH=/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/mingw/bin/:/c/mingw/bin:$PATH gcc --vertion"
  # - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c "where gcc"
  # - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c "where c++"
  # - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c "which gcc"
  - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c "PATH=/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/mingw/bin/:/c/mingw/bin:$PATH cd /c/projects/%APPVEYOR_PROJECT_NAME%; make clean"
  - C:\MinGW\msys\1.0\bin\bash.exe -i -l -c "PATH=/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/mingw/bin/:/c/mingw/bin:$PATH cd /c/projects/%APPVEYOR_PROJECT_NAME%; make VENDOR_SDK_VERSION=$VERSION"